### ISSUE TITLE
Type of bytesValue?

### ISSUE THREAD

**Issue by vladd11** [ydb-platform/ydb-nodejs-sdk#166]
On 21075 line of node_modules/ydb-sdk-proto/proto/bundle.d.ts I see:
```
/** Value bytesValue */
bytesValue?: (Uint8Array|null);
```
But when I run simple queries like:
```
const result = await session.executeQuery(`
SELECT id FROM table;
`)
```

It shows that result.resultSets[0].rows[0].bytesValue is actually `Buffer`, not `Uint8Array`.
Is this a mistake?

**Comment by nikolaymatrosov** [comment]
`Uint8Array` is a general-purpose byte array available in both NodeJS and browsers. `Buffer` is a [**subclass**](https://nodejs.org/api/buffer.html#buffer) of `Uint8Array` that’s only available in NodeJS (for historical reasons). Both are primarily used for manipulating binary (byte) data.

Historically, when NodeJS first came about, general-purpose Uint8Arrays didn’t exist, so it had to invent its own `Buffer` type for handling binary data. However, after general-purpose Uint8Arrays were introduced with es6, NodeJS (after version 4.0) decided to migrate Buffer over from a different data type to a subclass of Uint8Array (to try and make it more browser-compatible with Uint8Array).

**Comment by nikolaymatrosov** [comment]
If you are using `TypedData.createNativeObjects` method, you will not get the `bytesValue` that is a Buffer. Instead, SDK will [internally transform](https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/src/types.ts#L348) it to base64 encoded string.

So if you want to get Buffer back, you'll need to construct it yourself via `Buffer.from(val, 'base64')`.

**Comment by vladd11** [comment]
I'm taking values this way:
`result.resultSets[0].rows[0].items[0].bytesValue`

**Comment by nikolaymatrosov** [comment]
So you are ignoring all the conveniences SDK provides to make fetching data simpler.
Is there any reason behind this approach?

**Comment by vladd11** [comment]
It was personal opinion due to:
- better transparency for developer, I can just connect debugger and copy path to required output;
- more performant because SDK doing unnecessary things like converting to base64, finding type of the field, etc.

**Comment by tsufiev** [comment]
Actually, not everything was okay with Types.STRING and bytesValues, which was fixed in https://github.com/ydb-platform/ydb-nodejs-sdk/pull/177

More precisely, ydb-sdk code passed value of Types.STRING type as string literals to YDB which produced corrupted strings there. To maintain backwards compatibility, Types.STRING still behaves the same way, but now emits a warning about deprecation and removal in the next major version. The proper type to use for bytestring is Types.BYTES, introduced in version 3.4.0. It requires an explicit usage of Buffer type, both for sending data to YDB and when receiving data from it.
